apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodegymapp
spec:
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: nodegymapp
  template:
    metadata:
      labels:
        app: nodegymapp
    spec:
      containers:
      - name: nodegymapp
        image: gym:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
